version: '3.4'

services:
  frontend:
    entrypoint: "echo 'service disabled'"
    restart: "no"
  identifier:
    ports:
      - 80:80
  database:
    ports:
      - 8890:8890
  shmdoc-analyzer:
    ports:
      - 8891:8891
