version: '3.4'

services:
  frontend:
    image: shmdoc/frontend-shmdoc-osoc-poc
    links:
      - identifier:backend
  identifier:
    image: semtech/mu-identifier:1.9.0
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.19.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
  file:
    image: semtech/mu-file-service:3.1.2
    links:
      - database:database
    volumes:
      - ./data/files:/share
  shmdoc-analyzer:
    image: shmdoc/shmdoc-analyzer-service
    volumes:
      - ./data/files:/share
